### PR TITLE
chore: update gradle-plugin version to the latest and update README.md

### PR DESCRIPTION
**Pull request by taefi**
Also files that are being generated removed from the repo code.

### CODE REVIEW

**Comment by mvysny** [comment]
Vaadin v bump + vaadin gradle v bump looking good :+1: 

However, why are the `*.ts` and `package*` files removed? I think it's better to have them committed in the example app:
* When the user will run the app for the first time, they will be generated and since they're not in .gitingore, they will show in `git st`. What should the user do about them? Add to gitignore? No. Commit them? Yes, but why they're missing in the first place?
* They're also committed in Java Skeleton Starter to git: https://github.com/vaadin/skeleton-starter-flow

**Comment by taefi** [comment]
> However, why are the `*.ts` and `package*` files removed? 

Thanks, @mvysny. The removal idea came from not committing the auto-generated files. Although I get your point about keeping the skeleton from the start as it should end up in the user codebase, I'm still suggesting not to keep them in starter code by default.

IMO, having those bunch of config files (there are a lot of them, I even wanted to remove `webpack.config.js`) make it kinda scary for a newcomer to see them from the start. I think they are not making it feel at home for pure java developers, who normally don't (or prefer not to) have so much knowledge about the frontend stuff. I believe Vaadin should take care of them for the users, and having documentation somewhere e.g. in the README.md can make it clear for the users that those frontend-related files are being generated and it is up to them to commit them or not in their codebase. 

But in the end, I would bring them back if you think it is a better approach.

**Comment by mvysny** [comment]
> IMO, having those bunch of config files (there are a lot of them, I even wanted to remove webpack.config.js) make it kinda scary for a newcomer to see them from the start. I think they are not making it feel at home for pure java developers, who normally don't (or prefer not to) have so much knowledge about the frontend stuff. I believe Vaadin should take care of them for the users, and having documentation somewhere e.g. in the README.md can make it clear for the users that those frontend-related files are being generated and it is up to them to commit them or not in their codebase.

I wholeheartedly agree, and in such case it totally makes sense to remove/hide those JS-related files. Unfortunately Vaadin has decided differently, to expose/leak the JavaScript stuff onto the Java devs; and in such mindset I believe it makes sense to have the JS files in the root folder...

All I'm saying is that the Java+Maven-based quickstarters have those files committed in the git and it might probably make sense to follow the same practice with the Gradle starters as well...

**Comment by taefi** [comment]
> All I'm saying is that the Java+Maven-based quickstarters have those files committed in the git and it might probably make sense to follow the same practice with the Gradle starters as well... But it would be great if @mstahv or someone else from PD would provide more insight.

Agree, It is good to at least keep the uniformity. I'll bring back the deleted files.

**Comment by mstahv** [comment]
It is kind of nasty situation with all those front-end build files. For a typical Flow user, it would be best if those were not in the root of the project and not in source control management. But for Fusion users those are more relevant.

**Pull request closed without merging**
